import { Router } from 'express'
import PDFDocument from 'pdfkit'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { averageInventory, csv, ledgerValuation } from '../lib/reporting.js'
import { authenticate, requireTenant } from '../middleware/auth.js'

const router=Router();router.use(authenticate,requireTenant);const tid=(req:Express.Request)=>req.user!.tenantId!
const range=(query:unknown)=>{const q=z.object({from:z.coerce.date().optional(),to:z.coerce.date().optional(),groupBy:z.enum(['channel','category','product','customer','employee']).default('channel')}).parse(query),to=q.to??new Date(),from=q.from??new Date(to.getTime()-30*86400000);return{...q,from,to,previousFrom:new Date(from.getTime()-(to.getTime()-from.getTime())),previousTo:from}}

router.get('/dashboard',async(req,res)=>{const tenantId=tid(req),start=new Date();start.setHours(0,0,0,0);const[sales,newOrders,balances,expiring,receivables,recentOrders]=await Promise.all([prisma.order.aggregate({where:{tenantId,createdAt:{gte:start},status:{not:'CANCELLED'}},_sum:{total:true}}),prisma.order.count({where:{tenantId,createdAt:{gte:start}}}),prisma.inventoryBalance.groupBy({by:['productId'],where:{tenantId},_sum:{onHand:true,reserved:true}}),prisma.stockBatch.count({where:{tenantId,expiresAt:{gte:new Date(),lte:new Date(Date.now()+30*86400000)},quantity:{gt:0}}}),prisma.invoice.aggregate({where:{tenantId,status:{in:['OPEN','PARTIAL']}},_sum:{total:true}}),prisma.order.findMany({where:{tenantId},orderBy:{createdAt:'desc'},take:8})]);res.json({metrics:{todaySales:Number(sales._sum.total??0),newOrders,lowStock:balances.filter(x=>Number(x._sum.onHand??0)-Number(x._sum.reserved??0)<=5).length,expiringBatches:expiring,openReceivables:Number(receivables._sum.total??0)},recentOrders})})

async function salesRows(tenantId:string,query:unknown){const r=range(query),orders=await prisma.order.findMany({where:{tenantId,status:{not:'CANCELLED'},createdAt:{gte:r.previousFrom,lte:r.to}},include:{user:true,items:{include:{product:{include:{category:true}}}}}});const summarize=(from:Date,to:Date)=>{const map=new Map<string,{key:string;revenue:number;orders:Set<string>;quantity:number}>();for(const order of orders.filter(x=>x.createdAt>=from&&x.createdAt<=to)){const lines=r.groupBy==='channel'||r.groupBy==='customer'||r.groupBy==='employee'?[{key:r.groupBy==='channel'?order.channel:r.groupBy==='customer'?order.userId:order.user.name,amount:Number(order.total),quantity:order.items.reduce((s,i)=>s+i.quantity,0)}]:order.items.map(i=>({key:r.groupBy==='category'?i.product.category.name:i.product.name,amount:Number(i.unitPrice)*i.quantity,quantity:i.quantity}));for(const line of lines){const row=map.get(line.key)??{key:line.key,revenue:0,orders:new Set<string>(),quantity:0};row.revenue+=line.amount;row.orders.add(order.id);row.quantity+=line.quantity;map.set(line.key,row)}}return[...map.values()].map(x=>({key:x.key,revenue:x.revenue,orders:x.orders.size,quantity:x.quantity}))};const current=summarize(r.from,r.to),previous=summarize(r.previousFrom,r.previousTo);return{range:r,current:current.map(x=>({...x,previousRevenue:previous.find(p=>p.key===x.key)?.revenue??0,changePct:(previous.find(p=>p.key===x.key)?.revenue??0)>0?(x.revenue/(previous.find(p=>p.key===x.key)!.revenue)-1)*100:null}))}}
router.get('/sales',async(req,res)=>res.json(await salesRows(tid(req),req.query)))
router.get('/sales.csv',async(req,res)=>{const data=await salesRows(tid(req),req.query);res.type('text/csv').attachment('sales-report.csv').send(csv(['Огтлол','Орлого','Өмнөх орлого','Өөрчлөлт %','Захиалга','Тоо'],data.current.map(x=>[x.key,x.revenue,x.previousRevenue,x.changePct??'',x.orders,x.quantity])))})

async function operations(tenantId:string,days=90){const end=new Date(),since=new Date(end.getTime()-days*86400000),[products,movements,sales,pos,receipts,orderItems]=await Promise.all([prisma.product.findMany({where:{tenantId,active:true}}),prisma.stockMovement.findMany({where:{tenantId},orderBy:{createdAt:'asc'}}),prisma.stockMovement.findMany({where:{tenantId,type:'SALE',createdAt:{gte:since}}}),prisma.purchaseOrder.findMany({where:{tenantId},orderBy:{createdAt:'desc'}}),prisma.goodsReceipt.findMany({where:{tenantId},include:{lines:true}}),prisma.orderItem.findMany({where:{order:{tenantId,status:{not:'CANCELLED'},createdAt:{gte:since}}},include:{product:true}})]);const averages=averageInventory(movements,end,days),valuation=ledgerValuation(movements),sold=new Map<string,number>();sales.forEach(x=>sold.set(x.productId,(sold.get(x.productId)??0)+Math.abs(x.quantity)));const inventoryTurnover=products.map(p=>{const average=averages.get(p.id)??0;return{productId:p.id,name:p.name,sold:sold.get(p.id)??0,averageInventory:average,turnover:average>0?(sold.get(p.id)??0)/average:0}});const inventoryValuation=products.map(p=>({productId:p.id,name:p.name,quantity:valuation.get(p.id)?.quantity??0,value:valuation.get(p.id)?.value??0,averageCost:(valuation.get(p.id)?.quantity??0)>0?(valuation.get(p.id)!.value/valuation.get(p.id)!.quantity):0}));const supplierIds=[...new Set(pos.map(x=>x.supplierId))],suppliers=await prisma.supplier.findMany({where:{id:{in:supplierIds}}});const supplierPerformance=supplierIds.map(id=>{const supplierPos=pos.filter(x=>x.supplierId===id&&x.status!=='CANCELLED'),supplierReceipts=receipts.filter(x=>x.supplierId===id),ordered=supplierPos.reduce((s,po)=>s+supplierReceipts.filter(r=>r.purchaseOrderId===po.id).flatMap(r=>r.lines).reduce((a,l)=>a+l.expectedQuantity,0),0),accepted=supplierReceipts.flatMap(r=>r.lines).reduce((s,l)=>s+l.acceptedQuantity,0),onTime=supplierPos.filter(po=>po.expectedAt&&supplierReceipts.some(r=>r.purchaseOrderId===po.id&&r.receivedAt<=po.expectedAt!)).length;return{supplierId:id,name:suppliers.find(s=>s.id===id)?.name??id,purchaseOrders:supplierPos.length,onTimeRate:supplierPos.length?onTime/supplierPos.length:0,fillRate:ordered?accepted/ordered:0,discrepancyRate:ordered?supplierReceipts.flatMap(r=>r.lines).reduce((s,l)=>s+Math.abs(l.discrepancyQuantity),0)/ordered:0}});const marginByProduct=Object.values(orderItems.reduce<Record<string,{productId:string;name:string;revenue:number;cost:number;margin:number}>>((a,l)=>{const x=a[l.productId]??={productId:l.productId,name:l.product.name,revenue:0,cost:0,margin:0};x.revenue+=Number(l.netAmount||Number(l.unitPrice)*l.quantity);x.cost+=Number(l.product.costPrice)*l.quantity;x.margin=x.revenue-x.cost;return a},{}));return{periodDays:days,inventoryTurnover,inventoryValuation,totalInventoryValue:inventoryValuation.reduce((s,x)=>s+x.value,0),supplierPerformance,marginByProduct,expectedPO:pos.filter(x=>['SENT','PARTIALLY_RECEIVED'].includes(x.status))}}
router.get('/operations',async(req,res)=>res.json(await operations(tid(req),z.coerce.number().int().min(1).max(365).catch(90).parse(req.query.days))))
router.get('/operations.csv',async(req,res)=>{const d=await operations(tid(req));res.type('text/csv').attachment('operations-report.csv').send(csv(['Бараа','Зарагдсан','Дундаж үлдэгдэл','Эргэлт','Ledger үнэлгээ'],d.inventoryTurnover.map(x=>[x.name,x.sold,x.averageInventory,x.turnover,d.inventoryValuation.find(v=>v.productId===x.productId)?.value??0])))})
router.get('/supplier-performance.csv',async(req,res)=>{const d=await operations(tid(req));res.type('text/csv').attachment('supplier-performance.csv').send(csv(['Нийлүүлэгч','PO','Хугацаандаа %','Fill rate %','Зөрүү %'],d.supplierPerformance.map(x=>[x.name,x.purchaseOrders,x.onTimeRate*100,x.fillRate*100,x.discrepancyRate*100])))})
router.get('/operations.pdf',async(req,res)=>{const d=await operations(tid(req)),doc=new PDFDocument({margin:42}),chunks:Buffer[]=[];doc.on('data',x=>chunks.push(x));doc.on('end',()=>res.type('application/pdf').attachment('operations-report.pdf').send(Buffer.concat(chunks)));doc.fontSize(20).text('TradeFlow Operations Report').fontSize(11).text(`Ledger inventory value: ${d.totalInventoryValue.toLocaleString()} MNT`).moveDown();d.inventoryTurnover.slice(0,200).forEach(x=>doc.text(`${x.name} | avg ${x.averageInventory.toFixed(2)} | sold ${x.sold} | turnover ${x.turnover.toFixed(2)}`));doc.end()})
export default router
